services:
  web:
    build: .
    image: neuro-scan:latest
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - ./app/static/uploads:/app/app/static/uploads
    environment:
      - FLASK_APP=app/app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    restart: unless-stopped